### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by JamiKettunen** [JamiKettunen/Networking.cs#2]
## General
- [ ] Clear more variables on object re-initializations
- [ ] Add SSL server & client communication support
- [ ] Make System.Windows.Forms reference optional

## Client
- [x] Add a public connection timeout variable

## Server
- [ ] Add IPv6 support
- [ ] Handle NetworkStreams of clients in a better way
- [ ] Periodically check for closed connections to avoid ghost clients
